CompanyFinder.WebUI/Controllers/DataPolicyController.cs
using CompanyFinder.Business.Attributes;
using CompanyFinder.Business.Services.Abstract;
using CompanyFinder.Entities.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CompanyFinder.WebUI.Controllers
{
    [AuditLog]
    [ExceptionHandler]
    [Authorize(Roles = "Admins, SecondAdmins, HelperAdmins, AsistantAdmins, WorkerAdmins")]
    public class DataPolicyController : Controller
    {
        readonly IDataPolicyService _dataPolicyService;
        public DataPolicyController(IDataPolicyService dataPolicyService)
        {
            _dataPolicyService = dataPolicyService;
        }

        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            return View(await _dataPolicyService.GetAllAsync());
        }
        public async Task<IActionResult> kurtulusocL()
        {
            return View(await _dataPolicyService.GetAllAsync());
        }
        public async Task<IActionResult> DataPolicyOps()
        {
            return View(await _dataPolicyService.GetAllForAdmin());
        }
        public async Task<IActionResult> DataPolicyDetail(int? id)
        {
            return View(await _dataPolicyService.GetByIdAsync(id));
        }
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(DataPolicy model)
        {
            var result = await _dataPolicyService.CreateAsync(model);
            if (result)
            {
                TempData["dataPolicyCreatedSuccessfull"] = "Data Policy Created Successfull";
                return RedirectToAction(nameof(Create));
            }
            TempData["dataPolicyCreateError"] = "Data Policy Create Error";
            return RedirectToAction(nameof(Create));
        }
        public async Task<IActionResult> Edit(int? id)
        {
            var data = await _dataPolicyService.GetByIdAsync(id);
            if (data != null)
            {
                return View(data);
            }
            return RedirectToAction("Page404", "HomeAdmin");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(DataPolicy model)
        {
            var result = await _dataPolicyService.UpdateAsync(model);
            if (result)
            {
                TempData["dataPolicyUpdatedSuccessfull"] = "Data Policy Updated Successfull";
                return RedirectToAction(nameof(Edit), new { id = model.Id });
            }
            TempData["dataPolicyUpdateError"] = "Data Policy Update Error";
            return RedirectToAction(nameof(Edit), new { id = model.Id });
        }
        public async Task<IActionResult> Delete(int? id)
        {
            var data = await _dataPolicyService.GetByIdAsync(id);
            if (data != null)
            {
                return View(data);
            }
            return RedirectToAction("Page404", "HomeAdmin");
        }
        public async Task<IActionResult> DeleteDataPolicy(DataPolicy model, int id)
        {
            var result = await _dataPolicyService.DeleteAsync(model, id);
            if (result)
            {
                return RedirectToAction(nameof(DataPolicyOps));
            }
            return RedirectToAction("Page404", "HomeAdmin");
        }
        public async Task<IActionResult> SetActive(int id)
        {
            var result = await _dataPolicyService.SetActiveAsync(id);
            if (result)
            {
                return RedirectToAction(nameof(DataPolicyOps));
            }
            return RedirectToAction("Page404", "HomeAdmin");
        }
        public async Task<IActionResult> SetDeActive(int id)
        {
            var result = await _dataPolicyService.SetDeActiveAsync(id);
            if (result)
            {
                return RedirectToAction(nameof(DataPolicyOps));
            }
            return RedirectToAction("Page404", "HomeAdmin");
        }
        public async Task<IActionResult> SetDeleted(int id)
        {
            var result = await _dataPolicyService.SetDeletedAsync(id);
            if (result)
            {
                return RedirectToAction(nameof(DataPolicyOps));
            }
            return RedirectToAction("Page404", "HomeAdmin");
        }
        public async Task<IActionResult> SetNotDeleted(int id)
        {
            var result = await _dataPolicyService.SetNotDeletedAsync(id);
            if (result)
            {
                return RedirectToAction(nameof(DataPolicyOps));
            }
            return RedirectToAction("Page404", "HomeAdmin");
        }
    }
}

CompanyFinder.WebUI/Views/DataPolicy/Create.cshtml
@model DataPolicy
@{
	ViewData["Title"] = "Add A New Data Policy";
	ViewData["Subtitle"] = "Data Policy Navigator";
	Layout = "~/Views/Shared/_adminLayout.cshtml";
}

<div class="wrapper-pro">
	<div class="breadcome-area mg-b-30 small-dn">
		<div class="container-fluid">
			<div class="row">
				<div class="col-lg-12">
					<div class="breadcome-list map-mg-t-40-gl shadow-reset">
						<div class="row">
							<div class="col-lg-3 col-md-3 col-sm-3 col-xs-3">
								<div class="breadcome-heading">
									@ViewData["Subtitle"]
								</div>
							</div>
							<div class="col-lg-9 col-md-9 col-sm-9 col-xs-9">
								<ul class="breadcome-menu">
									<li>
										<a asp-controller="DataPolicy" asp-action="kurtulusocL">Data Policy Home</a> <span class="bread-slash">/</span>
									</li>
									<li>
										<a asp-controller="DataPolicy" asp-action="DataPolicyOps">Data Policy Ops</a> <span class="bread-slash">/</span>
									</li>
								</ul>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="basic-form-area mg-b-40">
		<div class="container-fluid">
			<div class="row">
				<div class="col-lg-12">
					<div class="sparkline12-list shadow-reset mg-t-30">
						<div class="sparkline12-hd">
							<div class="main-sparkline12-hd">
								<h1>@ViewData["Title"]</h1>
								<div class="sparkline12-outline-icon">
									<span class="sparkline12-collapse-link"><i class="fa fa-chevron-up"></i></span>
								</div>
							</div>
						</div>
						<div class="sparkline12-graph">
							<div class="basic-login-form-ad">
								<div class="row">
									<div class="col-lg-12">
										<div class="all-form-element-inner">
											<form asp-controller="DataPolicy" asp-action="Create" method="post">
												@Html.AntiForgeryToken()												
												<div class="form-group-inner">
													<div class="row">
														<div class="col-lg-12">
															<strong style="color:blue">Policy Title <span class="text-danger">*</span></strong>
															<input type="text" asp-for="Title" name="Title" class="form-control" required />
														</div>
													</div>
												</div>												
												<div class="form-group-inner">
													<div class="row">
														<div class="col-lg-12">
															<strong style="color:blue">Policy Description<span class="text-danger">*</span></strong>
															<textarea type="text" asp-for="Desc" name="Desc" class="ckeditor" required></textarea>
														</div>
													</div>
												</div>
												<div class="form-group-inner">
													<div class="login-btn-inner">
														<div class="row">
															<div class="col-lg-7"></div>
															<div class="col-lg-5">
																<div class="login-horizental cancel-wp pull-left">
																	<button class="btn btn-custon-rounded-four btn-primary" type="submit">Add Data Policy</button>
																	<a asp-controller="DataPolicy" asp-action="kurtulusocL" class="btn btn-custon-rounded-four btn-warning">Cancel</a>
																</div>
															</div>
														</div>
													</div>
												</div>
											</form>
											<partial name="_adminCrudAlertPartial" />
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

CompanyFinder.WebUI/Views/DataPolicy/DataPolicyDetail.cshtml
@model DataPolicy
@{
	ViewData["Title"] = "Data Policy Detail";
	ViewData["Subtitle"] = "Data Policy Navigator";
	Layout = "~/Views/Shared/_adminLayout.cshtml";
}

<div class="wrapper-pro">
	<div class="breadcome-area mg-b-30 small-dn">
		<div class="container-fluid">
			<div class="row">
				<div class="col-lg-12">
					<div class="breadcome-list map-mg-t-40-gl shadow-reset">
						<div class="row">
							<div class="col-lg-3 col-md-3 col-sm-3 col-xs-3">
								<div class="breadcome-heading">
									@ViewData["Subtitle"]
								</div>
							</div>
							<div class="col-lg-9 col-md-9 col-sm-9 col-xs-9">
								<ul class="breadcome-menu">
									<li>
										<a asp-controller="DataPolicy" asp-action="kurtulusocL">Data Policy Home</a> <span class="bread-slash">/</span>
									</li>
									<li>
										<a asp-controller="DataPolicy" asp-action="DataPolicyOps">Data Policy Ops</a> <span class="bread-slash">/</span>
									</li>
								</ul>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="project-details-area mg-b-40">
		<div class="container">
			<div class="row">
				<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
					<div class="project-details-wrap shadow-reset">
						<div class="row">
							<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
								<div class="project-details-mg">
									<div class="row">
										<div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
											<div class="project-details-st">
												<span><strong>Active Status:</strong></span>
											</div>
										</div>
										<div class="col-lg-8 col-md-8 col-sm-8 col-xs-12">
											<div class="btn-group project-list-ad">
												@if (Model.IsActive == true)
												{
													<button class="btn btn-white btn-xs">Active</button>
												}
												else
												{
													<button class="btn btn-white btn-xs">DeActive</button>
												}
											</div>
										</div>
									</div>
								</div>
								<div class="project-details-mg">
									<div class="row">
										<div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
											<div class="project-details-st">
												<span><strong>Deleted Status:</strong></span>
											</div>
										</div>
										<div class="col-lg-8 col-md-8 col-sm-8 col-xs-12">
											<div class="btn-group project-list-ad">
												@if (Model.IsDeleted == true)
												{
													<button class="btn btn-white btn-xs">Deleted</button>
												}
												else
												{
													<button class="btn btn-white btn-xs">Not Deleted</button>
												}
											</div>
										</div>
									</div>
								</div>
								<div class="project-details-mg">
									<div class="row">
										<div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
											<div class="project-details-st">
												<span><strong>Created Date:</strong></span>
											</div>
										</div>
										<div class="col-lg-8 col-md-8 col-sm-8 col-xs-12">
											<div class="project-details-dt">
												<span>@Model.CreatedDate.ToLongDateString()</span>
											</div>
										</div>
									</div>
								</div>
								<div class="project-details-mg">
									<div class="row">
										<div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
											<div class="project-details-st">
												<span><strong>Updated Date:</strong></span>
											</div>
										</div>
										<div class="col-lg-8 col-md-8 col-sm-8 col-xs-12">
											<div class="project-details-dt">
												@if (Model.UpdatedDate != null)
												{
													<span>@Model.UpdatedDate.Value.ToLongDateString()</span>
												}
												else
												{
													<span>---</span>
												}
											</div>
										</div>
									</div>
								</div>
							</div>
							<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
								<div class="project-details-mg">
									<div class="row">
										<div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
											<div class="project-details-st">
												<span><strong>ID No:</strong></span>
											</div>
										</div>
										<div class="col-lg-8 col-md-8 col-sm-8 col-xs-12">
											<div class="project-details-dt">
												<span>@Model.Id</span>
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>
						<div class="row">
							<div class="col-lg-12">
								<div class="project-details-tab">
									<ul class="nav nav-tabs res-pd-less-sm">
										<li class="active">
											<a data-toggle="tab" href="#menu1">@ViewData["Title"]</a>
										</li>
									</ul>
									<div class="tab-content res-tab-content-project">
										<div id="menu1" class="tab-pane fade in active animated zoomInLeft">
											<div class="project-details-completeness">
												<dl class="table table-striped">
													<dt class="col-sm-4">
														Policy Title
													</dt>
													<dd class="col-sm-8">
														@Model.Title
													</dd>
													<dt class="col-sm-4">
														Policy Description
													</dt>
													<dd class="col-sm-8">
														@Html.Raw(Model.Desc)
													</dd>
												</dl>
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

CompanyFinder.WebUI/Views/DataPolicy/DataPolicyOps.cshtml
@using System.Web
@model IEnumerable<DataPolicy>
@{
	ViewData["Title"] = "All Data Policy List";
	ViewData["Subtitle"] = "Data Policy Navigator";
	Layout = "~/Views/Shared/_adminLayout.cshtml";
}

<div class="wrapper-pro">
	<div class="breadcome-area mg-b-30 small-dn">
		<div class="container-fluid">
			<div class="row">
				<div class="col-lg-12">
					<div class="breadcome-list map-mg-t-40-gl shadow-reset">
						<div class="row">
							<div class="col-lg-3 col-md-3 col-sm-3 col-xs-3">
								<div class="breadcome-heading">
									@ViewData["Subtitle"]
								</div>
							</div>
							<div class="col-lg-9 col-md-9 col-sm-9 col-xs-9">
								<ul class="breadcome-menu">
									<li>
										<a asp-controller="DataPolicy" asp-action="kurtulusocL">Data Policy Home</a> <span class="bread-slash">/</span>
									</li>
									<li>
										<a asp-controller="DataPolicy" asp-action="DataPolicyOps">Data Policy Ops</a> <span class="bread-slash">/</span>
									</li>
								</ul>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="static-table-area mg-b-40">
		<div class="container-fluid">
			<div class="row">
				<div class="col-lg-12">
					<div class="sparkline12-list shadow-reset mg-t-30">
						<div class="sparkline12-hd">
							<div class="main-sparkline12-hd">
								<h1>@ViewData["Title"]</h1>
								<div class="sparkline12-outline-icon">
									<span>
										<a asp-controller="DataPolicy" asp-action="Create" class="btn btn-custon-rounded-two btn-primary">+ Add New One</a>
									</span>
									<span class="sparkline12-collapse-link"><i class="fa fa-chevron-up"></i></span>
								</div>
							</div>
						</div>
						<div class="sparkline12-graph">
							<div class="static-table-list">
								<table class="table hover-table">
									<thead>
										<tr>
											<th>Policy Title</th>
											<th>Policy Description</th>
											<th>Status</th>
											<th>Ops</th>
										</tr>
									</thead>
									<tbody>
										@foreach (var item in Model)
										{
											<tr>
												<td>
													@if (item.Title.Length > 85)
													{
														@HttpUtility.HtmlDecode(ReadMore.SafeSubstring(item.Title, 85) + " ...")
													}
													else
													{
														@item.Title
													}
												</td>
												<td>
													@if (item.Desc.Length > 155)
													{
														@Html.Raw(HttpUtility.HtmlDecode(ReadMore.SafeSubstring(item.Desc, 155) + " ..."))
													}
													else
													{
														@Html.Raw(item.Desc)
													}
												</td>
												<td>
													@if (item.IsActive == true)
													{
														<img src="~/img/statics/verification.png" class="img-responsive" style="max-height:25px;max-width:25px;min-height:25px;min-width:25px" asp-append-version="true" />
													}
													else
													{
														<img src="~/img/statics/cancelled.jpg" class="img-responsive" style="max-height:25px;max-width:25px;min-height:25px;min-width:25px" asp-append-version="true" />
													}
													@if (item.IsDeleted == true)
													{
														<img src="~/img/statics/delete.png" class="img-responsive" style="max-height:25px;max-width:25px;min-height:25px;min-width:25px" asp-append-version="true" />
													}
													else
													{
														<img src="~/img/statics/verification.png" class="img-responsive" style="max-height:25px;max-width:25px;min-height:25px;min-width:25px" asp-append-version="true" />
													}
												</td>
												<td>
													<a asp-controller="DataPolicy" asp-action="DataPolicyDetail" asp-route-id="@item.Id" class="btn btn-custon-rounded-three btn-info btn-sm">Detail</a>
													<a asp-controller="DataPolicy" asp-action="Edit" asp-route-id="@item.Id" class="btn btn-custon-rounded-three btn-success btn-sm">Edit</a>
													<a asp-controller="DataPolicy" asp-action="Delete" asp-route-id="@item.Id" class="btn btn-custon-rounded-three btn-danger btn-sm">Delete</a>
													@if (item.IsActive == true)
													{
														<a asp-controller="DataPolicy" asp-action="SetDeActive" asp-route-id="@item.Id" class="btn btn-custon-rounded-three btn-warning btn-sm">SetDeActive</a>
													}
													else
													{
														<a asp-controller="DataPolicy" asp-action="SetActive" asp-route-id="@item.Id" class="btn btn-custon-rounded-three btn-warning btn-sm">SetActive</a>
													}
													@if (item.IsDeleted == true)
													{
														<a asp-controller="DataPolicy" asp-action="SetNotDeleted" asp-route-id="@item.Id" class="btn btn-custon-rounded-three btn-warning btn-sm">SetNotDeleted</a>
													}
													else
													{
														<a asp-controller="DataPolicy" asp-action="SetDeleted" asp-route-id="@item.Id" class="btn btn-custon-rounded-three btn-warning btn-sm">SetDeleted</a>
													}
												</td>
											</tr>
										}
									</tbody>
								</table>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

CompanyFinder.WebUI/Views/DataPolicy/Delete.cshtml
@model DataPolicy
@{
	ViewData["Title"] = "Delete Data Policy";
	ViewData["Subtitle"] = "Data Policy Navigator";
	Layout = "~/Views/Shared/_adminLayout.cshtml";
}

<div class="wrapper-pro">
	<div class="breadcome-area mg-b-30 small-dn">
		<div class="container-fluid">
			<div class="row">
				<div class="col-lg-12">
					<div class="breadcome-list map-mg-t-40-gl shadow-reset">
						<div class="row">
							<div class="col-lg-3 col-md-3 col-sm-3 col-xs-3">
								<div class="breadcome-heading">
									@ViewData["Subtitle"]
								</div>
							</div>
							<div class="col-lg-9 col-md-9 col-sm-9 col-xs-9">
								<ul class="breadcome-menu">
									<li>
										<a asp-controller="DataPolicy" asp-action="kurtulusocL">Data Policy Home</a> <span class="bread-slash">/</span>
									</li>
									<li>
										<a asp-controller="DataPolicy" asp-action="DataPolicyOps">Data Policy Ops</a> <span class="bread-slash">/</span>
									</li>
								</ul>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="widgets-personal-info-area">
		<div class="container-fluid">
			<div class="row">
				<div class="col-lg-12">
					<div class="author-widgets-single widget-ov-mg-t-30 widget-ov-mg-t-n-30 widget-ov-mg-t-l-30 shadow-reset">
						<div class="persoanl-widget-hd persoanl1-widget-hd">
						</div>
						<div class="social-widget-result social-widget1-result">
							<span>Created At: @Model.CreatedDate.ToShortDateString()</span>
						</div>
						<div class="widget-text-box">
							<h4>Policy Title: @Model.Title</h4>
							<h4>
								Description: @Html.Raw(Model.Desc)
							</h4>
							@if (Model.UpdatedDate != null)
							{
								<p>Updated At: @Model.UpdatedDate.Value.ToShortDateString()</p>
							}
							@if (Model.IsActive == true)
							{
								<p>Active</p>
							}
							else
							{
								<p>DeActive</p>
							}
							@if (Model.IsDeleted == true)
							{
								<p>Deleted</p>
							}
							else
							{
								<p>Not Deleted</p>
							}
							<div class="text-right like-love-list">
								<a href="#" onclick="confirmDelete('DataPolicy', 'DeleteDataPolicy', @Model.Id); return false;" class="btn btn-custon-rounded-three btn-danger btn-sm"> Delete </a>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

CompanyFinder.WebUI/Views/DataPolicy/Edit.cshtml
@model DataPolicy
@{
	ViewData["Title"] = "Update Data Policy";
	ViewData["Subtitle"] = "Data Policy Navigator";
	Layout = "~/Views/Shared/_adminLayout.cshtml";
}

<div class="wrapper-pro">
	<div class="breadcome-area mg-b-30 small-dn">
		<div class="container-fluid">
			<div class="row">
				<div class="col-lg-12">
					<div class="breadcome-list map-mg-t-40-gl shadow-reset">
						<div class="row">
							<div class="col-lg-3 col-md-3 col-sm-3 col-xs-3">
								<div class="breadcome-heading">
									@ViewData["Subtitle"]
								</div>
							</div>
							<div class="col-lg-9 col-md-9 col-sm-9 col-xs-9">
								<ul class="breadcome-menu">
									<li>
										<a asp-controller="DataPolicy" asp-action="kurtulusocL">Data Policy Home</a> <span class="bread-slash">/</span>
									</li>
									<li>
										<a asp-controller="DataPolicy" asp-action="DataPolicyOps">Data Policy Ops</a> <span class="bread-slash">/</span>
									</li>
								</ul>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="basic-form-area mg-b-40">
		<div class="container-fluid">
			<div class="row">
				<div class="col-lg-12">
					<div class="sparkline12-list shadow-reset mg-t-30">
						<div class="sparkline12-hd">
							<div class="main-sparkline12-hd">
								<h1>@ViewData["Title"]</h1>
								<div class="sparkline12-outline-icon">
									<span class="sparkline12-collapse-link"><i class="fa fa-chevron-up"></i></span>
								</div>
							</div>
						</div>
						<div class="sparkline12-graph">
							<div class="basic-login-form-ad">
								<div class="row">
									<div class="col-lg-12">
										<div class="all-form-element-inner">
											<form asp-controller="DataPolicy" asp-action="Edit" method="post">
												@Html.AntiForgeryToken()
												<div class="form-group-inner">
													<div class="row">
														<div class="col-lg-12">
															<strong style="color:blue">Policy Title <span class="text-danger">*</span></strong>
															<input type="text" asp-for="Title" name="Title" class="form-control" required />
														</div>
													</div>
												</div>
												<div class="form-group-inner">
													<div class="row">
														<div class="col-lg-12">
															<strong style="color:blue">Policy Description<span class="text-danger">*</span></strong>
															<textarea type="text" asp-for="Desc" name="Desc" class="ckeditor" required></textarea>
														</div>
													</div>
												</div>
												<div class="form-group-inner">
													<div class="login-btn-inner">
														<div class="row">
															<div class="col-lg-7"></div>
															<div class="col-lg-5">
																<div class="login-horizental cancel-wp pull-left">
																	<button class="btn btn-custon-rounded-four btn-primary" type="submit">Update Data Policy</button>
																	<a asp-controller="DataPolicy" asp-action="kurtulusocL" class="btn btn-custon-rounded-four btn-warning">Cancel</a>
																</div>
															</div>
														</div>
													</div>
												</div>
											</form>
											<partial name="_adminCrudAlertPartial" />
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

CompanyFinder.WebUI/Views/DataPolicy/Index.cshtml
@model IEnumerable<DataPolicy>
@{
    ViewData["Title"] = "Kişisel Veriler ve Onların İşlenmesi";
    ViewData["Subtitle"] = "bi2bi.com Kişisel Veriler, Onların Toplanma Nedenleri ve Nasıl İşlendikleri Hakkında Aydınlatma Metni";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<section id="inner-banner">
    <div class="container">
        <div class="row">
            <div class="inner-heading">
                <h2>@ViewData["Title"]</h2>
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item active" aria-current="page">@ViewData["Subtitle"]</li>
                    </ol>
                </nav>
            </div>
        </div>
    </div>
</section>
<section id="faq">
    <div class="container">
        <div class="col-md-12">
            <div id="accordion">
                @foreach (var item in Model)
                {
                    <div class="card">
                        <div class="card-header" id="headingOne">
                            <h5 class="mb-0">
                                <button class="btn btn-link" data-toggle="collapse" data-target="#@item.Id" aria-expanded="true" aria-controls="collapseOne">
                                    <span class="s_no">@item.Title</span>
                                </button>
                            </h5>
                        </div>
                        <div id="@item.Id" class="collapse" aria-labelledby="headingOne" data-parent="#accordion">
                            <div class="card-body">
                                <p>@Html.Raw(item.Desc)</p>
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</section>

CompanyFinder.WebUI/Views/DataPolicy/kurtulusocL.cshtml
@using System.Web
@model IEnumerable<DataPolicy>
@{
	ViewData["Title"] = "Active Data Policy List";
	ViewData["Subtitle"] = "Data Policy Navigator";
	Layout = "~/Views/Shared/_adminLayout.cshtml";
}

<div class="wrapper-pro">
	<div class="breadcome-area mg-b-30 small-dn">
		<div class="container-fluid">
			<div class="row">
				<div class="col-lg-12">
					<div class="breadcome-list map-mg-t-40-gl shadow-reset">
						<div class="row">
							<div class="col-lg-3 col-md-3 col-sm-3 col-xs-3">
								<div class="breadcome-heading">
									@ViewData["Subtitle"]
								</div>
							</div>
							<div class="col-lg-9 col-md-9 col-sm-9 col-xs-9">
								<ul class="breadcome-menu">
									<li>
										<a asp-controller="DataPolicy" asp-action="kurtulusocL">Data Policy Home</a> <span class="bread-slash">/</span>
									</li>
									<li>
										<a asp-controller="DataPolicy" asp-action="DataPolicyOps">Data Policy Ops</a> <span class="bread-slash">/</span>
									</li>
								</ul>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="static-table-area mg-b-40">
		<div class="container-fluid">
			<div class="row">
				<div class="col-lg-12">
					<div class="sparkline12-list shadow-reset mg-t-30">
						<div class="sparkline12-hd">
							<div class="main-sparkline12-hd">
								<h1>@ViewData["Title"]</h1>
								<div class="sparkline12-outline-icon">
									<span>
										<a asp-controller="DataPolicy" asp-action="Create" class="btn btn-custon-rounded-two btn-primary">+ Add New One</a>
									</span>
									<span class="sparkline12-collapse-link"><i class="fa fa-chevron-up"></i></span>
								</div>
							</div>
						</div>
						<div class="sparkline12-graph">
							<div class="static-table-list">
								<table class="table hover-table table-striped">
									<thead>
										<tr>
											<th>Policy Title</th>
											<th>Policy Description</th>
											<th>Ops</th>
										</tr>
									</thead>
									<tbody>
										@foreach (var item in Model)
										{
											<tr>
												<td>
													@if (item.Title.Length > 85)
													{
														@HttpUtility.HtmlDecode(ReadMore.SafeSubstring(item.Title, 85) + " ...")
													}
													else
													{
														@item.Title
													}
												</td>
												<td>
													@if (item.Desc.Length > 155)
													{
														@Html.Raw(HttpUtility.HtmlDecode(ReadMore.SafeSubstring(item.Desc, 155) + " ..."))
													}
													else
													{
														@Html.Raw(item.Desc)
													}
												</td>
												<td>
													<a asp-controller="DataPolicy" asp-action="DataPolicyDetail" asp-route-id="@item.Id" class="btn btn-custon-rounded-three btn-info btn-sm">Detail</a>
													<a asp-controller="DataPolicy" asp-action="Edit" asp-route-id="@item.Id" class="btn btn-custon-rounded-three btn-success btn-sm">Edit</a>
												</td>
											</tr>
										}
									</tbody>
								</table>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>