CompanyFinder.WebUI/Controllers/PictureController.cs
using CompanyFinder.Business.Attributes;
using CompanyFinder.Business.Services.Abstract;
using CompanyFinder.Entities.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CompanyFinder.WebUI.Controllers
{
    [AuditLog]
    [ExceptionHandler]
    [Authorize(Roles = "Admins, SecondAdmins, HelperAdmins, AsistantAdmins, WorkerAdmins")]
    public class PictureController : Controller
    {
        readonly IPictureService _pictureService;
        public PictureController(IPictureService pictureService)
        {
            _pictureService = pictureService;
        }
        public async Task<IActionResult> kurtulusocL()
        {
            return View(await _pictureService.GetAllIncludingAsync());
        }
        public async Task<IActionResult> BlogImage(int? id)
        {
            return View(await _pictureService.GetAllIncludingByBlogIdAsync(id));
        }
        public async Task<IActionResult> CompanyImage(int? id)
        {
            return View(await _pictureService.GetAllIncludingByCompanyIdAsync(id));
        }
        public async Task<IActionResult> ProductImage(int? id)
        {
            return View(await _pictureService.GetAllIncludingByProductIdAsync(id));
        }
        public async Task<IActionResult> BlogImageForAdmin(int? id)
        {
            return View(await _pictureService.GetAllIncludingByBlogIdForAdminAsync(id));
        }
        public async Task<IActionResult> CompanyImageForAdmin(int? id)
        {
            return View(await _pictureService.GetAllIncludingByCompanyIdForAdminAsync(id));
        }
        public async Task<IActionResult> ProductImageForAdmin(int? id)
        {
            return View(await _pictureService.GetAllIncludingByProductIdForAdminAsync(id));
        }
        public async Task<IActionResult> PictureOps()
        {
            return View(await _pictureService.GetAllIncludingForAdmin());
        }
        public async Task<IActionResult> PictureDetail(int? id)
        {
            return View(await _pictureService.GetByIdAsync(id));
        }
        public async Task<IActionResult> Delete(int? id)
        {
            var data = await _pictureService.GetByIdAsync(id);
            if (data != null)
            {
                return View(data);
            }
            return RedirectToAction("Page404", "HomeAdmin");
        }
        public async Task<IActionResult> DeletePicture(Picture model, int id)
        {
            var result = await _pictureService.DeleteAsync(model, id);
            if (result)
            {
                return RedirectToAction(nameof(PictureOps));
            }
            return RedirectToAction("Page404", "HomeAdmin");
        }
        public async Task<IActionResult> SetActive(int id)
        {
            var result = await _pictureService.SetActiveAsync(id);
            if (result)
            {
                return RedirectToAction(nameof(PictureOps));
            }
            return RedirectToAction("Page404", "HomeAdmin");
        }
        public async Task<IActionResult> SetDeActive(int id)
        {
            var result = await _pictureService.SetDeActiveAsync(id);
            if (result)
            {
                return RedirectToAction(nameof(PictureOps));
            }
            return RedirectToAction("Page404", "HomeAdmin");
        }
        public async Task<IActionResult> SetDeleted(int id)
        {
            var result = await _pictureService.SetDeletedAsync(id);
            if (result)
            {
                return RedirectToAction(nameof(PictureOps));
            }
            return RedirectToAction("Page404", "HomeAdmin");
        }
        public async Task<IActionResult> SetNotDeleted(int id)
        {
            var result = await _pictureService.SetNotDeletedAsync(id);
            if (result)
            {
                return RedirectToAction(nameof(PictureOps));
            }
            return RedirectToAction("Page404", "HomeAdmin");
        }
    }
}

CompanyFinder.WebUI/Views/Picture/BlogImage.cshtml
@model IEnumerable<Picture>
@{
	ViewData["Title"] = "Active Blog Picture List";
	ViewData["Subtitle"] = "Picture Navigator";
	Layout = "~/Views/Shared/_adminLayout.cshtml";
}

<div class="wrapper-pro">
	<div class="breadcome-area mg-b-30 small-dn">
		<div class="container-fluid">
			<div class="row">
				<div class="col-lg-12">
					<div class="breadcome-list map-mg-t-40-gl shadow-reset">
						<div class="row">
							<div class="col-lg-3 col-md-3 col-sm-3 col-xs-3">
								<div class="breadcome-heading">
									@ViewData["Subtitle"]
								</div>
							</div>
							<div class="col-lg-9 col-md-9 col-sm-9 col-xs-9">
								<ul class="breadcome-menu">
									<li>
										<a asp-controller="Picture" asp-action="kurtulusocL">Picture Home</a> <span class="bread-slash">/</span>
									</li>
									<li>
										<a asp-controller="Picture" asp-action="PictureOps">Picture Ops</a> <span class="bread-slash">/</span>
									</li>
								</ul>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="data-table-area mg-b-40">
		<div class="container-fluid">
			<div class="row">
				<div class="col-lg-12">
					<div class="sparkline13-list shadow-reset">
						<div class="sparkline13-hd">
							<div class="main-sparkline13-hd">
								<h1>@ViewData["Title"] </h1>
								<div class="sparkline13-outline-icon">
									<span class="sparkline13-collapse-link"><i class="fa fa-chevron-up"></i></span>
								</div>
							</div>
						</div>
						<div class="sparkline13-graph">
							<div class="datatable-dashv1-list custom-datatable-overright">
								<div id="toolbar">
									<select class="form-control">
										<option value="">Export Basic</option>
										<option value="all">Export All</option>
										<option value="selected">Export Selected</option>
									</select>
								</div>
								<table id="table"
									   data-toggle="table"
									   data-pagination="true"
									   data-resizable="true"
									   data-search="true"
									   data-show-columns="true"
									   data-show-pagination-switch="true"
									   data-show-refresh="true"
									   data-key-events="true"
									   data-show-toggle="true"
									   data-cookie="true"
									   data-cookie-id-table="saveId"
									   data-show-export="true"
									   data-click-to-select="true"
									   data-toolbar="#toolbar">
									<thead>
										<tr>
											<th data-field="state" data-checkbox="true"></th>
											<th data-field="id">ID</th>
											<th data-field="image">Image</th>
											<th data-field="imageFrom">Image From</th>
											<th>Ops</th>
										</tr>
									</thead>
									<tbody>
										@foreach (var item in Model)
										{
											<tr>
												<td></td>
												<td>@item.Id</td>
												<td>
													@if (item.BlogId != null || item.CompanyId != null || item.ProductId != null)
													{
														if (item.BlogId != null)
														{
															<img src="~/img/company/blog/multiImage/@item.ImageUrl" style="max-height:100px;max-width:100px;min-height:100px;min-width:100px;" class="img-responsive" asp-append-version="true" />
														}
														if (item.CompanyId != null)
														{
															<img src="~/img/company/images/@item.ImageUrl" style="max-height:100px;max-width:100px;min-height:100px;min-width:100px;" class="img-responsive" asp-append-version="true" />
														}
														if (item.ProductId != null)
														{
															<img src="~/img/company/product/multiImage/@item.ImageUrl" style="max-height:100px;max-width:100px;min-height:100px;min-width:100px;" class="img-responsive" asp-append-version="true" />
														}
													}
													else
													{
														<strong style="color:darkred">No Any Image</strong>
													}
												</td>
												<td>
													@if (item.BlogId != null)
													{
														<ul>
															<li>Blog Image</li>
															<li>BlogId: @item.BlogId</li>
															<li>Blog Title: @item.Blog.Title</li>
															@if (item.Blog.Company != null)
															{
																<li>Blog CompanyId: @item.Blog.CompanyId</li>
																<li>Blog Company: @item.Blog.Company.Name</li>
															}
															else
															{
																<li><strong style="color:darkred">No Blog Company</strong></li>
															}
														</ul>
														<a asp-controller="Picture" asp-action="BlogImageForAdmin" asp-route-id="@item.BlogId" class="btn btn-custon-rounded-two btn-primary">
															See All Images for Admin
														</a>
													}
													else
													{
														<strong style="color:darkred">Not Information</strong>
													}
												</td>
												<td>
													<a asp-controller="Picture" asp-action="PictureDetail" asp-route-id="@item.Id" class="btn btn-custon-rounded-two btn-info btn-sm">Detail</a>
												</td>
											</tr>
										}
									</tbody>
								</table>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

CompanyFinder.WebUI/Views/Picture/BlogImageForAdmin.cshtml
@model IEnumerable<Picture>
@{
	ViewData["Title"] = "Active Blog Picture List For Admin";
	ViewData["Subtitle"] = "Picture Navigator";
	Layout = "~/Views/Shared/_adminLayout.cshtml";
}

<div class="wrapper-pro">
	<div class="breadcome-area mg-b-30 small-dn">
		<div class="container-fluid">
			<div class="row">
				<div class="col-lg-12">
					<div class="breadcome-list map-mg-t-40-gl shadow-reset">
						<div class="row">
							<div class="col-lg-3 col-md-3 col-sm-3 col-xs-3">
								<div class="breadcome-heading">
									@ViewData["Subtitle"]
								</div>
							</div>
							<div class="col-lg-9 col-md-9 col-sm-9 col-xs-9">
								<ul class="breadcome-menu">
									<li>
										<a asp-controller="Picture" asp-action="kurtulusocL">Picture Home</a> <span class="bread-slash">/</span>
									</li>
									<li>
										<a asp-controller="Picture" asp-action="PictureOps">Picture Ops</a> <span class="bread-slash">/</span>
									</li>
								</ul>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="data-table-area mg-b-40">
		<div class="container-fluid">
			<div class="row">
				<div class="col-lg-12">
					<div class="sparkline13-list shadow-reset">
						<div class="sparkline13-hd">
							<div class="main-sparkline13-hd">
								<h1>@ViewData["Title"] </h1>
								<div class="sparkline13-outline-icon">
									<span class="sparkline13-collapse-link"><i class="fa fa-chevron-up"></i></span>
								</div>
							</div>
						</div>
						<div class="sparkline13-graph">
							<div class="datatable-dashv1-list custom-datatable-overright">
								<div id="toolbar">
									<select class="form-control">
										<option value="">Export Basic</option>
										<option value="all">Export All</option>
										<option value="selected">Export Selected</option>
									</select>
								</div>
								<table id="table"
									   data-toggle="table"
									   data-pagination="true"
									   data-resizable="true"
									   data-search="true"
									   data-show-columns="true"
									   data-show-pagination-switch="true"
									   data-show-refresh="true"
									   data-key-events="true"
									   data-show-toggle="true"
									   data-cookie="true"
									   data-cookie-id-table="saveId"
									   data-show-export="true"
									   data-click-to-select="true"
									   data-toolbar="#toolbar">
									<thead>
										<tr>
											<th data-field="state" data-checkbox="true"></th>
											<th data-field="id">ID</th>
											<th data-field="image">Image</th>
											<th data-field="imageFrom">Image From</th>
											<th>Ops</th>
										</tr>
									</thead>
									<tbody>
										@foreach (var item in Model)
										{
											<tr>
												<td></td>
												<td>@item.Id</td>
												<td>
													@if (item.BlogId != null || item.CompanyId != null || item.ProductId != null)
													{
														if (item.BlogId != null)
														{
															<img src="~/img/company/blog/multiImage/@item.ImageUrl" style="max-height:100px;max-width:100px;min-height:100px;min-width:100px;" class="img-responsive" asp-append-version="true" />
														}
														if (item.CompanyId != null)
														{
															<img src="~/img/company/images/@item.ImageUrl" style="max-height:100px;max-width:100px;min-height:100px;min-width:100px;" class="img-responsive" asp-append-version="true" />
														}
														if (item.ProductId != null)
														{
															<img src="~/img/company/product/multiImage/@item.ImageUrl" style="max-height:100px;max-width:100px;min-height:100px;min-width:100px;" class="img-responsive" asp-append-version="true" />
														}
													}
													else
													{
														<strong style="color:darkred">No Any Image</strong>
													}
												</td>
												<td>
													@if (item.BlogId != null)
													{
														<ul>
															<li>Blog Image</li>
															<li>BlogId: @item.BlogId</li>
															<li>Blog Title: @item.Blog.Title</li>
															@if (item.Blog.Company != null)
															{
																<li>Blog CompanyId: @item.Blog.CompanyId</li>
																<li>Blog Company: @item.Blog.Company.Name</li>
															}
															else
															{
																<li><strong style="color:darkred">No Blog Company</strong></li>
															}
														</ul>
														<a asp-controller="Picture" asp-action="BlogImage" asp-route-id="@item.BlogId" class="btn btn-custon-rounded-two btn-primary">
															See All Images
														</a>
													}
													else
													{
														<strong style="color:darkred">Not Information</strong>
													}
												</td>
												<td>
													<a asp-controller="Picture" asp-action="PictureDetail" asp-route-id="@item.Id" class="btn btn-custon-rounded-two btn-info btn-sm">Detail</a>
												</td>
											</tr>
										}
									</tbody>
								</table>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

CompanyFinder.WebUI/Views/Picture/CompanyImage.cshtml
@model IEnumerable<Picture>
@{
	ViewData["Title"] = "Active Company Picture List";
	ViewData["Subtitle"] = "Picture Navigator";
	Layout = "~/Views/Shared/_adminLayout.cshtml";
}

<div class="wrapper-pro">
	<div class="breadcome-area mg-b-30 small-dn">
		<div class="container-fluid">
			<div class="row">
				<div class="col-lg-12">
					<div class="breadcome-list map-mg-t-40-gl shadow-reset">
						<div class="row">
							<div class="col-lg-3 col-md-3 col-sm-3 col-xs-3">
								<div class="breadcome-heading">
									@ViewData["Subtitle"]
								</div>
							</div>
							<div class="col-lg-9 col-md-9 col-sm-9 col-xs-9">
								<ul class="breadcome-menu">
									<li>
										<a asp-controller="Picture" asp-action="kurtulusocL">Picture Home</a> <span class="bread-slash">/</span>
									</li>
									<li>
										<a asp-controller="Picture" asp-action="PictureOps">Picture Ops</a> <span class="bread-slash">/</span>
									</li>
								</ul>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="data-table-area mg-b-40">
		<div class="container-fluid">
			<div class="row">
				<div class="col-lg-12">
					<div class="sparkline13-list shadow-reset">
						<div class="sparkline13-hd">
							<div class="main-sparkline13-hd">
								<h1>@ViewData["Title"] </h1>
								<div class="sparkline13-outline-icon">
									<span class="sparkline13-collapse-link"><i class="fa fa-chevron-up"></i></span>
								</div>
							</div>
						</div>
						<div class="sparkline13-graph">
							<div class="datatable-dashv1-list custom-datatable-overright">
								<div id="toolbar">
									<select class="form-control">
										<option value="">Export Basic</option>
										<option value="all">Export All</option>
										<option value="selected">Export Selected</option>
									</select>
								</div>
								<table id="table"
									   data-toggle="table"
									   data-pagination="true"
									   data-resizable="true"
									   data-search="true"
									   data-show-columns="true"
									   data-show-pagination-switch="true"
									   data-show-refresh="true"
									   data-key-events="true"
									   data-show-toggle="true"
									   data-cookie="true"
									   data-cookie-id-table="saveId"
									   data-show-export="true"
									   data-click-to-select="true"
									   data-toolbar="#toolbar">
									<thead>
										<tr>
											<th data-field="state" data-checkbox="true"></th>
											<th data-field="id">ID</th>
											<th data-field="image">Image</th>
											<th data-field="imageFrom">Image From</th>
											<th>Ops</th>
										</tr>
									</thead>
									<tbody>
										@foreach (var item in Model)
										{
											<tr>
												<td></td>
												<td>@item.Id</td>
												<td>
													@if (item.BlogId != null || item.CompanyId != null || item.ProductId != null)
													{
														if (item.BlogId != null)
														{
															<img src="~/img/company/blog/multiImage/@item.ImageUrl" style="max-height:100px;max-width:100px;min-height:100px;min-width:100px;" class="img-responsive" asp-append-version="true" />
														}
														if (item.CompanyId != null)
														{
															<img src="~/img/company/images/@item.ImageUrl" style="max-height:100px;max-width:100px;min-height:100px;min-width:100px;" class="img-responsive" asp-append-version="true" />
														}
														if (item.ProductId != null)
														{
															<img src="~/img/company/product/multiImage/@item.ImageUrl" style="max-height:100px;max-width:100px;min-height:100px;min-width:100px;" class="img-responsive" asp-append-version="true" />
														}
													}
													else
													{
														<strong style="color:darkred">No Any Image</strong>
													}
												</td>
												<td>
													@if (item.CompanyId != null)
													{
														<ul>
															<li>Company Image</li>
															<li>Company Id: @item.CompanyId</li>
															<li>Company: @item.Company.Name</li>
														</ul>
														<a asp-controller="Picture" asp-action="CompanyImageForAdmin" asp-route-id="@item.CompanyId" class="btn btn-custon-rounded-two btn-primary">
															See All Images for Admin
														</a>
													}
													else
													{
														<strong style="color:darkred">Not Information</strong>
													}
												</td>
												<td>
													<a asp-controller="Picture" asp-action="PictureDetail" asp-route-id="@item.Id" class="btn btn-custon-rounded-two btn-info btn-sm">Detail</a>
												</td>
											</tr>
										}
									</tbody>
								</table>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

CompanyFinder.WebUI/Views/Picture/CompanyImageForAdmin.cshtml
@model IEnumerable<Picture>
@{
	ViewData["Title"] = "Active Company Picture List For Admin";
	ViewData["Subtitle"] = "Picture Navigator";
	Layout = "~/Views/Shared/_adminLayout.cshtml";
}

<div class="wrapper-pro">
	<div class="breadcome-area mg-b-30 small-dn">
		<div class="container-fluid">
			<div class="row">
				<div class="col-lg-12">
					<div class="breadcome-list map-mg-t-40-gl shadow-reset">
						<div class="row">
							<div class="col-lg-3 col-md-3 col-sm-3 col-xs-3">
								<div class="breadcome-heading">
									@ViewData["Subtitle"]
								</div>
							</div>
							<div class="col-lg-9 col-md-9 col-sm-9 col-xs-9">
								<ul class="breadcome-menu">
									<li>
										<a asp-controller="Picture" asp-action="kurtulusocL">Picture Home</a> <span class="bread-slash">/</span>
									</li>
									<li>
										<a asp-controller="Picture" asp-action="PictureOps">Picture Ops</a> <span class="bread-slash">/</span>
									</li>
								</ul>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="data-table-area mg-b-40">
		<div class="container-fluid">
			<div class="row">
				<div class="col-lg-12">
					<div class="sparkline13-list shadow-reset">
						<div class="sparkline13-hd">
							<div class="main-sparkline13-hd">
								<h1>@ViewData["Title"] </h1>
								<div class="sparkline13-outline-icon">
									<span class="sparkline13-collapse-link"><i class="fa fa-chevron-up"></i></span>
								</div>
							</div>
						</div>
						<div class="sparkline13-graph">
							<div class="datatable-dashv1-list custom-datatable-overright">
								<div id="toolbar">
									<select class="form-control">
										<option value="">Export Basic</option>
										<option value="all">Export All</option>
										<option value="selected">Export Selected</option>
									</select>
								</div>
								<table id="table"
									   data-toggle="table"
									   data-pagination="true"
									   data-resizable="true"
									   data-search="true"
									   data-show-columns="true"
									   data-show-pagination-switch="true"
									   data-show-refresh="true"
									   data-key-events="true"
									   data-show-toggle="true"
									   data-cookie="true"
									   data-cookie-id-table="saveId"
									   data-show-export="true"
									   data-click-to-select="true"
									   data-toolbar="#toolbar">
									<thead>
										<tr>
											<th data-field="state" data-checkbox="true"></th>
											<th data-field="id">ID</th>
											<th data-field="image">Image</th>
											<th data-field="imageFrom">Image From</th>
											<th>Ops</th>
										</tr>
									</thead>
									<tbody>
										@foreach (var item in Model)
										{
											<tr>
												<td></td>
												<td>@item.Id</td>
												<td>
													@if (item.BlogId != null || item.CompanyId != null || item.ProductId != null)
													{
														if (item.BlogId != null)
														{
															<img src="~/img/company/blog/multiImage/@item.ImageUrl" style="max-height:100px;max-width:100px;min-height:100px;min-width:100px;" class="img-responsive" asp-append-version="true" />
														}
														if (item.CompanyId != null)
														{
															<img src="~/img/company/images/@item.ImageUrl" style="max-height:100px;max-width:100px;min-height:100px;min-width:100px;" class="img-responsive" asp-append-version="true" />
														}
														if (item.ProductId != null)
														{
															<img src="~/img/company/product/multiImage/@item.ImageUrl" style="max-height:100px;max-width:100px;min-height:100px;min-width:100px;" class="img-responsive" asp-append-version="true" />
														}
													}
													else
													{
														<strong style="color:darkred">No Any Image</strong>
													}
												</td>
												<td>
													@if (item.CompanyId != null)
													{
														<ul>
															<li>Company Image</li>
															<li>Company Id: @item.CompanyId</li>
															<li>Company: @item.Company.Name</li>
														</ul>
														<a asp-controller="Picture" asp-action="CompanyImage" asp-route-id="@item.CompanyId" class="btn btn-custon-rounded-two btn-primary">
															See All Images
														</a>
													}
													else
													{
														<strong style="color:darkred">Not Information</strong>
													}
												</td>
												<td>
													<a asp-controller="Picture" asp-action="PictureDetail" asp-route-id="@item.Id" class="btn btn-custon-rounded-two btn-info btn-sm">Detail</a>
												</td>
											</tr>
										}
									</tbody>
								</table>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

CompanyFinder.WebUI/Views/Picture/Delete.cshtml
@model Picture
@{
	ViewData["Title"] = "Delete Picture";
	ViewData["Subtitle"] = "Picture Navigator";
	Layout = "~/Views/Shared/_adminLayout.cshtml";
}

<div class="wrapper-pro">
	<div class="breadcome-area mg-b-30 small-dn">
		<div class="container-fluid">
			<div class="row">
				<div class="col-lg-12">
					<div class="breadcome-list map-mg-t-40-gl shadow-reset">
						<div class="row">
							<div class="col-lg-3 col-md-3 col-sm-3 col-xs-3">
								<div class="breadcome-heading">
									@ViewData["Subtitle"]
								</div>
							</div>
							<div class="col-lg-9 col-md-9 col-sm-9 col-xs-9">
								<ul class="breadcome-menu">
									<li>
										<a asp-controller="Picture" asp-action="kurtulusocL">Picture Home</a> <span class="bread-slash">/</span>
									</li>
									<li>
										<a asp-controller="Picture" asp-action="PictureOps">Picture Ops</a> <span class="bread-slash">/</span>
									</li>
								</ul>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="widgets-personal-info-area">
		<div class="container-fluid">
			<div class="row">
				<div class="col-lg-12">
					<div class="author-widgets-single widget-ov-mg-t-30 widget-ov-mg-t-n-30 widget-ov-mg-t-l-30 shadow-reset">
						<div class="perso-img">
							@if (Model.BlogId != null || Model.CompanyId != null || Model.ProductId != null)
							{
								if (Model.BlogId != null)
								{
									@await Component.InvokeAsync("DeleteBlogImage", new { id = Model.BlogId })
								}
								if (Model.CompanyId != null)
								{
									@await Component.InvokeAsync("DeleteCompanyImage", new { id = Model.CompanyId })
								}
								if (Model.ProductId != null)
								{
									@await Component.InvokeAsync("DeleteProductImage", new { id = Model.ProductId })
								}
							}
							else
							{
								<strong style="color:darkred">No Any Image</strong>
							}
						</div>
						<div class="widget-text-box">
							<h4>Image From</h4>
							@if (Model.BlogId != null || Model.CompanyId != null || Model.ProductId != null)
							{
								if (Model.BlogId != null)
								{
									<ul>
										<li>Blog Image</li>
										<li>BlogId: @Model.BlogId</li>
										<li>Blog Title: @Model.Blog.Title</li>
										@if (Model.Blog.Company != null)
										{
											<li>Blog CompanyId: @Model.Blog.CompanyId</li>
											<li>Blog Company: @Model.Blog.Company.Name</li>
										}
										else
										{
											<li><strong style="color:darkred">No Blog Company</strong></li>
										}
									</ul>
								}
								if (Model.CompanyId != null)
								{
									<ul>
										<li>Company Image</li>
										<li>Company Id: @Model.CompanyId</li>
										<li>Company: @Model.Company.Name</li>
									</ul>
								}
								if (Model.ProductId != null)
								{
									<ul>
										<li>Procuct Image</li>
										<li>ProductId: @Model.ProductId</li>
										<li>Product: @Model.Product.Name</li>
										@if (Model.Product.CompanyId != null)
										{
											<li>Product CompanyId: @Model.Product.CompanyId</li>
											<li>Product Company: @Model.Product.Company.Name</li>
										}
										else
										{
											<li><strong style="color:darkred">No Product Company</strong></li>
										}
									</ul>
								}
							}
							else
							{
								<strong style="color:darkred">Not Information</strong>
							}
							@if (Model.UpdatedDate != null)
							{
								<p>Updated At: @Model.UpdatedDate.Value.ToShortDateString()</p>
							}
							@if (Model.IsActive == true)
							{
								<p>Active</p>
							}
							else
							{
								<p>DeActive</p>
							}
							@if (Model.IsDeleted == true)
							{
								<p>Deleted</p>
							}
							else
							{
								<p>Not Deleted</p>
							}
							<div class="text-right like-love-list">
								<a href="#" onclick="confirmDelete('Picture', 'DeletePicture', @Model.Id); return false;" class="btn btn-custon-rounded-three btn-danger btn-sm"> Delete </a>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>